plugin:
    name: 'digitfab.core::lang.plugin.name'
    description: 'digitfab.core::lang.plugin.description'
    author: 'Evgeny Epifanov'
    icon: icon-cog
    homepage: 'https://digitfab.ru'
permissions:
    digitfab.core.settings:
        tab: 'digitfab.core::lang.company'
        label: 'digitfab.core::lang.settings'
    digitfab.core.contacts:
        tab: 'digitfab.core::lang.company'
        label: 'digitfab.core::lang.contacts'
    digitfab.core.addresses:
        tab: 'digitfab.core::lang.company'
        label: 'digitfab.core::lang.addresses'
    digitfab.core.socials:
        tab: 'digitfab.core::lang.company'
        label: 'digitfab.core::lang.social_networks'
    digitfab.core.opening_hours:
        tab: 'digitfab.core::lang.company'
        label: 'digitfab.core::lang.opening_hours'
    digitfab.core.manage-widgets:
        tab: 'digitfab.core::lang.widgets'
        label: 'digitfab.core::lang.manage-widgets'
navigation:
    company:
        label: 'digitfab.core::lang.company'
        url: digitfab/core/contactcontroller
        icon: icon-edit
        sideMenu:
            contacts:
                label: 'digitfab.core::lang.contacts'
                url: digitfab/core/contactcontroller
                icon: icon-book
                permissions:
                    - digitfab.core.contacts
            addresses:
                label: 'digitfab.core::lang.addresses'
                url: digitfab/core/addresscontroller
                icon: icon-map-marker
                permissions:
                    - digitfab.core.addresses
            socials:
                label: 'digitfab.core::lang.social_networks'
                url: digitfab/core/socialcontroller
                icon: icon-users
                permissions:
                    - digitfab.core.socials
            opening-hours:
                label: 'digitfab.core::lang.opening_hours'
                url: digitfab/core/workingperiodcontroller
                icon: icon-clock-o
                permissions:
                    - digitfab.core.opening_hours
    widgets:
        label: 'digitfab.core::lang.widgets'
        url: digitfab/core/widgetcontroller
        icon: icon-bars
        permissions:
            - digitfab.core.manage-widgets