list: $/digitfab/core/models/social/columns.yaml
modelClass: DigitFab\Core\Models\Social
title: 'digitfab.core::lang.social_networks'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'digitfab/core/socialcontroller/update/:id'
