name: 'digitfab.core::lang.social_network'
form: $/digitfab/core/models/social/fields.yaml
modelClass: DigitFab\Core\Models\Social
defaultRedirect: digitfab/core/socialcontroller
create:
    title: 'digitfab.core::lang.creating'
    redirect: 'digitfab/core/socialcontroller/update/:id'
    redirectClose: digitfab/core/socialcontroller
    flashSave: 'digitfab.core::lang.saved'
update:
    title: 'digitfab.core::lang.editing'
    redirect: digitfab/core/socialcontroller
    redirectClose: digitfab/core/socialcontroller
    flashSave: 'digitfab.core::lang.saved'
