name: 'digitfab.core::lang.contact'
modelClass: DigitFab\Core\Models\Contact
form: $/digitfab/core/models/contact/fields.yaml
defaultRedirect: digitfab/core/contactcontroller
create:
    title: 'digitfab.core::lang.creating'
    redirect: 'digitfab/core/contactcontroller/update/:id'
    redirectClose: digitfab/core/contactcontroller
    flashSave: 'digitfab.core::lang.saved'
update:
    title: 'digitfab.core::lang.editing'
    redirect: digitfab/core/contactcontroller
    redirectClose: digitfab/core/contactcontroller
    flashSave: 'digitfab.core::lang.saved'
preview: {  }
