list: $/digitfab/core/models/contact/columns.yaml
modelClass: DigitFab\Core\Models\Contact
title: 'digitfab.core::lang.contacts'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'digitfab/core/contactcontroller/update/:id'
