title: 'eev.core::lang.opening_hours'
modelClass: EEV\Core\Models\WorkingPeriod
list: $/eev/core/models/workingperiod/columns.yaml
recordUrl: 'eev/core/workingperiodcontroller/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
