name: 'digitfab.core::lang.opening_hours'
form: $/digitfab/core/models/workingperiod/fields.yaml
modelClass: DigitFab\Core\Models\WorkingPeriod
defaultRedirect: digitfab/core/workingperiodcontroller
create:
    title: 'digitfab.core::lang.creating'
    redirect: 'digitfab/core/workingperiodcontroller/update/:id'
    redirectClose: digitfab/core/workingperiodcontroller
    flashSave: 'digitfab.core::lang.saved'
update:
    title: 'digitfab.core::lang.editing'
    redirect: digitfab/core/workingperiodcontroller
    redirectClose: digitfab/core/workingperiodcontroller
    flashSave: 'digitfab.core::lang.saved'
