name: 'digitfab.core::lang.address'
modelClass: DigitFab\Core\Models\Address
form: $/digitfab/core/models/address/fields.yaml
defaultRedirect: digitfab/core/addresscontroller
create:
    title: 'digitfab.core::lang.creating'
    redirect: 'digitfab/core/addresscontroller/update/:id'
    redirectClose: digitfab/core/addresscontroller
    flashSave: 'digitfab.core::lang.saved'
update:
    title: 'digitfab.core::lang.editing'
    redirect: digitfab/core/addresscontroller
    redirectClose: digitfab/core/addresscontroller
    flashSave: 'digitfab.core::lang.saved'
preview: {  }
