title: 'eev.core::lang.addresses'
modelClass: EEV\Core\Models\Address
list: $/eev/core/models/address/columns.yaml
recordUrl: 'eev/core/addresscontroller/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
