name: 'eev.core::lang.address'
modelClass: EEV\Core\Models\Address
form: $/eev/core/models/address/fields.yaml
defaultRedirect: eev/core/addresscontroller
create:
    title: 'eev.core::lang.creating'
    redirect: 'eev/core/addresscontroller/update/:id'
    redirectClose: eev/core/addresscontroller
    flashSave: 'eev.core::lang.saved'
update:
    title: 'eev.core::lang.editing'
    redirect: eev/core/addresscontroller
    redirectClose: eev/core/addresscontroller
    flashSave: 'eev.core::lang.saved'
preview: {  }
