name: 'digitfab.core::lang.widget'
form: $/digitfab/core/models/widget/fields.yaml
modelClass: DigitFab\Core\Models\Widget
defaultRedirect: digitfab/core/widgetcontroller
create:
    title: 'digitfab.core::lang.creating'
    redirect: 'digitfab/core/widgetcontroller/update/:id'
    redirectClose: digitfab/core/widgetcontroller
    flashSave: 'digitfab.core::lang.saved'
update:
    title: 'digitfab.core::lang.editing'
    redirect: digitfab/core/widgetcontroller
    redirectClose: digitfab/core/widgetcontroller
    flashSave: 'digitfab.core::lang.saved'
